name: Tag and Publish Release
on:
  push:
    branches:
      - main

jobs:
  tag-and-publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Tag release
        run: |
          version=$(cat VERSION)
          git tag $version
          git push origin $version
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build sdist and wheel
        run: python -m build --sdist --wheel outdir dist/
      - name: Publish to TEST PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
